// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/companies": {
            "get": {
                "description": "This API for getting list of companies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "ListCompanies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.CompanyStruct"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "post": {
                "description": "This API for creating a new company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "CreateCompany",
                "parameters": [
                    {
                        "description": "CompanyCreateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CreateCompany"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.CompanyStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        },
        "/v1/companies/{id}": {
            "get": {
                "description": "This API for getting company detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "GetCompany",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CompanyId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.CompanyStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "put": {
                "description": "This API for updating company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "UpdateCompany",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CompanyId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "CompanyUpdateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CompanyStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.CompanyStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "This API for deleting the company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "DeleteCompany",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CompanyId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        },
        "/v1/packages": {
            "get": {
                "description": "This API for getting list of packages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "package"
                ],
                "summary": "GetListPackages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SetId",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.PackageStruct"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "post": {
                "description": "This API for creating a new package",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "package"
                ],
                "summary": "CreatePackage",
                "parameters": [
                    {
                        "description": "PackageCreateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CreatePackage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.PackageStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        },
        "/v1/packages/{id}": {
            "get": {
                "description": "This API for getting package detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "package"
                ],
                "summary": "GetPackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PackageId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.PackageStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "put": {
                "description": "This API for updating package",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "package"
                ],
                "summary": "UpdateSetUpdatePackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PackageId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PackageUpdateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.PackageStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.PackageStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "This API for deleting the package",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "package"
                ],
                "summary": "DeletePackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PackageId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        },
        "/v1/services": {
            "get": {
                "description": "This API for getting list of services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "ListServices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CompanyId",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.ServiceStruct"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "post": {
                "description": "This API for creating a new service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "CreateService",
                "parameters": [
                    {
                        "description": "ServiceCreateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CreateService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ServiceStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        },
        "/v1/services/{id}": {
            "get": {
                "description": "This API for getting service detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "GetService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ServiceStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "put": {
                "description": "This API for updating service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "UpdateService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ServiceUpdateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.ServiceStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ServiceStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "This API for deleting the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "DeleteService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        },
        "/v1/sets": {
            "get": {
                "description": "This API for getting list of sets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "set"
                ],
                "summary": "GetListSets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceId",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/structs.SetStruct"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "post": {
                "description": "This API for creating a new set",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "set"
                ],
                "summary": "CreateSet",
                "parameters": [
                    {
                        "description": "SetCreateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CreateSet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.SetStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        },
        "/v1/sets/{id}": {
            "get": {
                "description": "This API for getting set detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "set"
                ],
                "summary": "GetSet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SetId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.SetStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "put": {
                "description": "This API for updating set",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "set"
                ],
                "summary": "UpdateSet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SetId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SetUpdateRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.SetStruct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.SetStruct"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "This API for deleting the set",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "set"
                ],
                "summary": "DeleteSet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SetId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structs.StandardErrorModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "structs.CompanyStruct": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Services  ServiceStruct ` + "`" + `json:\"serviceStruct\"` + "`" + `",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                },
                "slogan": {
                    "$ref": "#/definitions/structs.Language"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "structs.CreateCompany": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                },
                "slogan": {
                    "$ref": "#/definitions/structs.Language"
                }
            }
        },
        "structs.CreatePackage": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                },
                "description": {
                    "$ref": "#/definitions/structs.Language"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                },
                "setId": {
                    "type": "integer"
                }
            }
        },
        "structs.CreateService": {
            "type": "object",
            "properties": {
                "companyId": {
                    "type": "integer"
                },
                "description": {
                    "$ref": "#/definitions/structs.Language"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                }
            }
        },
        "structs.CreateSet": {
            "type": "object",
            "properties": {
                "description": {
                    "$ref": "#/definitions/structs.Language"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                },
                "serviceId": {
                    "type": "integer"
                }
            }
        },
        "structs.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "structs.Language": {
            "type": "object",
            "properties": {
                "ki": {
                    "type": "string"
                },
                "ru": {
                    "type": "string"
                },
                "uz": {
                    "type": "string"
                }
            }
        },
        "structs.PackageStruct": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "$ref": "#/definitions/structs.Language"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                },
                "setId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "structs.ServiceStruct": {
            "type": "object",
            "properties": {
                "companyId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "$ref": "#/definitions/structs.Language"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "structs.SetStruct": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "$ref": "#/definitions/structs.Language"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "$ref": "#/definitions/structs.Language"
                },
                "serviceId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "structs.StandardErrorModel": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/structs.Error"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
